### ISSUE TITLE
Riak link issue while Object Creation

### ISSUE THREAD

**Issue by ashishsme14** [nicholasjhenry/technology-radar#25]
We had written below code but we getting error as -

`$ curl http://localhost:8098/riak/hb/friendship/_,_,_`

Error we getting as -

<HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>

Please help us

**Comment by nicholasjhenry** [comment]
Unfortunately, I won't be able to help you, but I suggest posting your problem to StackOverflow: https://stackoverflow.com. All the best.
